# We can use "Exception" concept with multiple ways:

def main():  # suppose this is my function.
    print("Hello World!!")


main()  # calling a function

# There is another alternate way which is an older way of using it. (Refer Lab_138)
